services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: pizzeria
    volumes:
      - postgres:/data/postgres
      - ./srs/main/resources/db-init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: unless-stopped
volumes:
  postgres:
    driver: local

